Reading Data from HDF5

```{r}
created = h5createFile("example.h5")
created
```

Once HDF5 file is is created, you can create groups within the file:

```{r}
created = h5createGroup("example.h5","foo")
created = h5createGroup("example.h5","baa") ## ^^ these two calls will create groups in the parent filed

created = h5createGroup("example.h5","foo/foobaa")
## the / in the expression above will create a foobaa group within foo of the parent

h5ls("example.h5") # like list file command but for h5 file
```

To write to groups:

```{r}
A = matrix(1:10, nr=5, nc=2)
h5write(A, "example.h5", "foo/A")
#Above will write in variable A, within the HDF5 group, 
B = array(seq(0.1, 2.0, by=0.1), dim=c(5,2,2))
attr(B, "scale") <- "liter"
h5write(B, "example.h5", "foo/foobaa/B")
h5ls("example.h5")
```

Writing a data set

```{r}
df = data.frame(1L:5L, seq(0,1,length.out=5),
               c("ab","cde","fghi","a","s"), stringsAsFactors=FALSE)
h5write(df, "example.h5", "df")
h5ls("example.h5")
```

To read data from HDF5 files:

```{r}
readA = h5read("example.h5","foo/A")
readB = h5read("example.h5","foo/foobaa/B")
readdf= h5read("example.h5","df")
readA
```

Writing and reading chunks:

```{r}
h5write(c(12,13,14),"example.h5", "foo/A", index=list(1:3,1))
#Above writes into the data set A, the elements 12, 13, 14 at the index provided
h5read("example.h5", "foo/A")
```

